name: build mschange.prx
on:
  push: {tags:  ['v*']} #  Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write

jobs:
  build_mschange:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    
    - name: prepare pspsdk docker
      run: |
        docker pull ghcr.io/pspdev/pspsdk:latest
        docker run -d -it --rm -v $(pwd):/project --name pspsdk_run ghcr.io/pspdev/pspsdk

    - name: build psp prx
      run: |
        chmod +x ./script/*.sh
        docker exec -i pspsdk_run bash -c "cd /project/script && export PSPSDK=$PSPDEV && ./build_mschange.sh"

    - name: create a release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "./build/mschange.prx"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}